# Template/UIConfigs.py

import pygame

# --- CONFIGURAÇÕES DO PYGAME ---
FPS = 60

# --- CONFIGURAÇÕES DE TELA E GRID ---
TAMANHO_QUADRADO = 100
NUM_LINHAS = 5         
NUM_COLUNAS = 9        
GRID_OFFSET_X = 50
GRID_OFFSET_Y = 150  
TAMANHO_CAIPORA = TAMANHO_QUADRADO
TAMANHO_BP = 130 # Bicho Papão maior
TAMANHO_BRUXA = 120 # Bruxa

# Dimensões calculadas da tela (para o ScreenManager)
LARGURA_TELA = NUM_COLUNAS * TAMANHO_QUADRADO + (2 * GRID_OFFSET_X)
ALTURA_TELA = NUM_LINHAS * TAMANHO_QUADRADO + (2 * GRID_OFFSET_Y)
TITULO_JOGO = "Folclore Game - Modularizado"

# --- CONFIGURAÇÕES DE UI E CORES ---
PRETO = (0, 0, 0)
BRANCO = (255, 255, 255)
VERMELHO = (200, 50, 50)  
VERDE_ATIVO = (50, 200, 50) 

LARGURA_BOTAO_ADD = 180
ALTURA_BOTAO = 50
BOTAO_PAUSE_X = LARGURA_TELA - 150
BOTAO_PAUSE_LARGURA = 100